### ISSUE TITLE
python_odoo with ipython

### ISSUE THREAD

**Issue by bwrsandman** [anybox/anybox.recipe.odoo#12]
@veloutin showed me this awesome patch he makes to python_odoo to use an ipython console to take advantage of its features.

Could this be officially added to the recipe?

```patch
--- bin/python_odoo	2014-07-25 15:11:16.467096106 -0400
+++ bin/python_odoo	2014-07-25 15:11:05.073762648 -0400
@@ -66,4 +66,9 @@
 
 if _interactive:
     del _interactive
+    try:
+        import IPython
+    except ImportError:
+        __import__("code").interact(banner="", local=globals())
+    else:
+        IPython.start_ipython(user_ns=globals())
-    __import__("code").interact(banner="", local=globals())
```

**Comment by leorochael** [comment]
Hi folks.

No need to patch anything. 

If you just add `ipython` to the `eggs` and `openerp_scripts` settings of your `anybox.recipe.odoo` buildout part you'll get an `ipython_odoo` intepreter in the same context as `python_odoo` right now.

See example here:
https://gist.github.com/leorochael/888f1a728b227676244c

**Comment by lmignon** [comment]
@leorochael Thank you for the tip. What do you think to make a PR to puts this information in the doc.

**Comment by bwrsandman** [comment]
That's cool. However, as far as this project is concerned, ipython is incomplete as the openerp `session` is not opened.

**Comment by leorochael** [comment]
@bwrsandman, I've updated [the gist](https://gist.github.com/leorochael/888f1a728b227676244c) with information on how to pass `session` into the IPython namespace (and did the same for for `bpython`) by using the `arguments` option of `openerp_scripts`.

Passing the whole `globals()`, or omitting or changing the banner could similarly be done by manipulating `arguments` as well.

**Comment by bwrsandman** [comment]
Nice. `command-line-options=-d` is not necessary.

Can I ask why, you added the egg ipython[notebook] before. When trying `bin/ipython_odoo notebook, I get.
```bash
$ bin/ipython_odoo notebook
TypeError('find_module() takes exactly 3 arguments (2 given)',)
> /usr/lib64/python2.7/pkgutil.py(475)find_loader()
    474     for importer in iter_importers(fullname):
--> 475         loader = importer.find_module(fullname)
    476         if loader is not None:
```

**Comment by leorochael** [comment]
True `-d` is not necessary, I just thought it was a good example of showing how the options for `odoo_scripts` can apply to interactive interpreters as well.

I hand't actually tried the IPython notebook but I was going to. I removed it from the gist because:

 * it's not necessary for the purposes of this discussion
 * it pulls in even more dependencies, some of which require more system packages (libzmq-dev, for instance)
 * it'll likely require extra code to work

Regarding the last point: buildout (actually `zc.recipe.egg:scripts`) generates scritpts in `bin/` that manually insert a lot of paths (mostly eggs) in `sys.path`, because buildout does not install them on the Python library path by design.

However, these inserted paths are not propagated to subprocesses by default, since they aren't in `os.env['PYTHONPATH']` either.

Now IPython notebook launches kernels as subprocesses, so they're not going to see the extra paths.

So, even though I haven't tried yet, I believe the only way of getting IPython notebook to run in an "odoo server" context is to import and instantiate an `a.r.o.runtime.session.Session` object manually inside the notebook, since it's in a different process than the generated script).

And that will only be possible if the generated script somehow export its own `sys.path` into the `PYTHONPATH` environment before launching kernels.

And all this seems still to be unrelated to the error you got.

**Comment by petrus-v** [comment]
@leorochael,

Thanks for the gist! 

As @lmignon :+1: to add it in the documentation!
