### ISSUE TITLE
How do you deal with  [Errno 104] Connection reset by peer?

### ISSUE THREAD

**Issue by agb80** [anybox/anybox.recipe.odoo#62]
More than an issue this is a support request, on the time we have been using the buildout recipe we often have been to deal with buildout script crashing because of  [Errno 104] Connection reset by peer during the eggs download phase.

I know is a problem with our internet connection that had a temporal issue communicating with pip database, but unfortunately we cannot do anything to improve the situation on the technical side.

Until now the way we deal with the problem is restarting the buildout compilation as many times as needed for a successful build. Unfortunately that's very tie consuming and not the ideal behavior.

How do you deal with this situation? Is there any buildout option that could help wit this?

**Comment by lmignon** [comment]
@agb80 take a look at https://pypi.python.org/pypi/zc.buildout/2.4.1#socket-timeout

**Comment by lefeverd** [comment]
We have the same problem, and unfortunately it seems that raising the socket-timeout has no effect.
If it doesn't already exists maybe we should propose some kind of retry option?

**Comment by agb80** [comment]
Same than @lefeverd and according to [this](https://bitbucket.org/pypa/setuptools/issues/217/retry-downloads-to-avoid-error-errno-104) is an issue with pip but no solution provided yet.

**Comment by lmignon** [comment]
@rvalyi here it is your answer to your tweet

**Comment by agb80** [comment]
I found a work around for this situation, create a default.cfg configuration file for buildout, inside a folder named ```.buildout``` into your home folder. The file must have follow lines:

```
[buildout]
eggs-directory = /home/agustin/.buildout/eggs
download-cache = /home/agustin/.buildout/downloads
extends-cache = /home/agustin/.buildout/extends
openerp-downloads-directory = /home/agustin/.buildout/openerp-downloads
newest = false
```

the first four lines are optional but recommended for optimize the hard disc space usage and share eggs between projects, but the real important line is the last one, that indicates buildout do not check for new eggs on pipy, so once and egg is already present on ```eggs-directory``` folder bouldout don't ask pipy for it anymore.

**Comment by petrus-v** [comment]
Hi @agb80,

Also at Anybox we are using our own pypi server using [pypiserver](https://pypi.python.org/pypi/pypiserver) as cache server for some package that are often giving a timeout.

then in the main buildout config
```
[buildout]
# this exposes some download utility sites of anybox to the public,
# and that's ok. We may restrict bandwith though.
index = http://pypi.exemple.fr/

# this directives below avoid crawling lots of non-download URLs related to
# projects that don't host their packages directly on PyPI.
# Such crawling ddos'es some of them, and that leads to buildout errors
# which we want to avoid.
# Situation has been somewhat mitigated by introduction in PyPI of a boolean
# flag to say upfront that no project-related site should be crawled for
# package downloads.
allow-hosts = *.exemple.fr
              pypi.python.org
```

We are using ``eggs-directory`` and ``openerp-downloads-directory``, I think ``download-cache`` and ``extends-cache`` should be use knowing what you do as long (it could be a nightmare to understand what's happen if you forgot extends files are cached, In main case using extends from server file I would prefer it's stop than using previous cached file silently).

@gracinet, Is our pipy server ready to use for the odoo community?

Regards,
Pierre

**Comment by gracinet** [comment]
On 09/01/2015 10:44 AM, Pierre Verkest wrote:
>
> Hi @agb80 <https://github.com/agb80>,
>
> Also at Anybox we are using our own pypi server using pypiserver
> <https://pypi.python.org/pypi/pypiserver> as cache server for some
> package that are often giving a timeout.
>
> then in the main buildout config
>
> |[buildout]
> # this exposes some download utility sites of anybox to the public,
> # and that's ok. We may restrict bandwith though.
> index = http://pypi.exemple.fr/
>
> # this directives below avoid crawling lots of non-download URLs related to
> # projects that don't host their packages directly on PyPI.
> # Such crawling ddos'es some of them, and that leads to buildout errors
> # which we want to avoid.
> # Situation has been somewhat mitigated by introduction in PyPI of a boolean
> # flag to say upfront that no project-related site should be crawled for
> # package downloads.
> allow-hosts = *.exemple.fr
>               pypi.python.org
> |
>
> We are using |eggs-directory| and |openerp-downloads-directory|, I
> think |download-cache| and |extends-cache| should be use knowing what
> you do as long (it could be a nightmare to understand what's happen if
> you forgot extends files are cached, In main case using extends from
> server file I would prefer it's stop than using previous cached file
> silently).
>
> @gracinet <https://github.com/gracinet>, Is our pipy server ready to
> use for the odoo community?
>
I don't think it would be of much benefit to the community. It was
useful for ourselves because it has structurally less traffic than PyPI,
and we could repackage some distributions (Pychart…) in it for easier
and more controlled access (avoiding the crawling as that comment of
mine above says).

To deal with this, we have used a combination of several approaches

* the pypiserver + restriction of our servers to use it
* a whole PyPI mirror, which I happily ditched when PyPI got CDN-backed
* aggressive caching (eggs-directory)
* beforehand freezing and extraction, up to repackaging eggs in Debian
archives

Overall, while I empathize with your problems, @agb80, the situation has
become much better in general, and Github looks to be a more frequent
source of troubles for us than PyPI. That's because on one hand there
are less exceptional distributions nowadays, and on the other hand, PyPI
itself is stronger. It really seems therefore that your issues are more
related to your internet connection  than something global. I don't what
your scale is, but deploying a local instance of PyPI server and having
it taking care of the most frequent libraries could help you and give
you more flexibility in cases you want to step out of the newest=False
(which you'll need to do from time to time).

Cheers,

**Comment by agb80** [comment]
@gracinet indeed that is a problem on my end, if you read my first comment I said I knew it, just asking to see if there were someone else having same situation that comes with a solution. And the ones you are proposing are amazing, specially the PyPi server. Thank you very much

**Comment by agb80** [comment]
@petrus-v thank you too!

**Comment by petrus-v** [comment]
@agb80 with pleasure, so I close the issue!
